import { describe, it, expect } from 'vitest';
import { parseHaas } from '../../converters/haas/parser';
import { writeHaas } from '../../converters/haas/writer';
import type { Tool } from '../../types/tool';

// ── Fixtures ─────────────────────────────────────────────────────────────────

const FORMAT_A = `%
(TOOL OFFSETS - Generated by CNC Tool Converter)
(  TOOL  LENGTH GEOMETRY  LENGTH WEAR   DIA GEOMETRY   DIA WEAR  DESCRIPTION        CLNT POS)
(    1     200.0000         0.0000        0.5000         0.0000   1/2 ENDMILL               0)
(    2     195.3750         0.0050        0.2500         0.0010   1/4 DRILL                 0)
(    3     182.0000         0.0000        0.3750         0.0000   3/8 BALL MILL             0)
%`;

const MINIMAL_TOOL: Tool = {
  id: 'test-id-1',
  toolNumber: 1,
  type: 'flat end mill',
  description: '10mm End Mill',
  unit: 'mm',
  geometry: { diameter: 10 },
  offsets: { z: 150.0 },
};

// ── Parser tests ──────────────────────────────────────────────────────────────

describe('HAAS parser', () => {
  it('parses tool numbers from Format A', async () => {
    const result = await parseHaas(FORMAT_A, 'offsets.ofs');
    expect(result.errors).toHaveLength(0);
    expect(result.tools).toHaveLength(3);
    expect(result.tools[0].toolNumber).toBe(1);
    expect(result.tools[1].toolNumber).toBe(2);
    expect(result.tools[2].toolNumber).toBe(3);
  });

  it('parses diameter (DIA GEOMETRY column)', async () => {
    const result = await parseHaas(FORMAT_A, 'offsets.ofs');
    expect(result.tools[0].geometry.diameter).toBeCloseTo(0.5);
    expect(result.tools[1].geometry.diameter).toBeCloseTo(0.25);
    expect(result.tools[2].geometry.diameter).toBeCloseTo(0.375);
  });

  it('stores LENGTH GEOMETRY in offsets.z', async () => {
    const result = await parseHaas(FORMAT_A, 'offsets.ofs');
    expect(result.tools[0].offsets?.z).toBeCloseTo(200.0);
    expect(result.tools[1].offsets?.z).toBeCloseTo(195.375);
    expect(result.tools[2].offsets?.z).toBeCloseTo(182.0);
  });

  it('parses description from DESCRIPTION column', async () => {
    const result = await parseHaas(FORMAT_A, 'offsets.ofs');
    expect(result.tools[0].description).toBe('1/2 ENDMILL');
    expect(result.tools[1].description).toBe('1/4 DRILL');
    expect(result.tools[2].description).toBe('3/8 BALL MILL');
  });

  it('preserves wear offsets in sourceData', async () => {
    const result = await parseHaas(FORMAT_A, 'offsets.ofs');
    expect((result.tools[1].sourceData as Record<string, number>).haasLengthWear).toBeCloseTo(0.005);
    expect((result.tools[1].sourceData as Record<string, number>).haasDiaWear).toBeCloseTo(0.001);
  });

  it('skips tape delimiter and header lines', async () => {
    const result = await parseHaas(FORMAT_A, 'offsets.ofs');
    expect(result.tools).toHaveLength(3);
  });

  it('returns warning and zero tools for empty file', async () => {
    const result = await parseHaas('%\n%', 'empty.ofs');
    expect(result.tools).toHaveLength(0);
    expect(result.warnings.length).toBeGreaterThan(0);
  });

  it('handles ArrayBuffer input', async () => {
    const buf = new TextEncoder().encode(FORMAT_A).buffer;
    const result = await parseHaas(buf, 'test.ofs');
    expect(result.tools).toHaveLength(3);
  });
});

// ── Writer tests ──────────────────────────────────────────────────────────────

describe('HAAS writer', () => {
  it('produces Format A parenthesised lines', async () => {
    const result = await writeHaas([MINIMAL_TOOL]);
    expect(result.content).toMatch(/^%/m);
    // Should have parenthesised data line for tool 1
    expect(result.content).toMatch(/\(\s*1\s/);
  });

  it('writes correct filename extension', async () => {
    const result = await writeHaas([MINIMAL_TOOL], { filename: 'my-machine' });
    expect(result.filename).toBe('my-machine.ofs');
  });

  it('writes diameter from geometry.diameter', async () => {
    const result = await writeHaas([MINIMAL_TOOL]);
    expect(result.content).toContain('10.0000');
  });

  it('writes length offset from offsets.z', async () => {
    const result = await writeHaas([MINIMAL_TOOL]);
    expect(result.content).toContain('150.0000');
  });

  it('includes header and tape delimiter lines', async () => {
    const result = await writeHaas([MINIMAL_TOOL]);
    expect(result.content).toMatch(/^%/m);
    expect(result.content).toMatch(/TOOL.*LENGTH/i);
  });

  it('warns on duplicate tool numbers', async () => {
    const t2 = { ...MINIMAL_TOOL, id: 'test-id-2', toolNumber: 1 };
    const result = await writeHaas([MINIMAL_TOOL, t2]);
    expect(result.warnings.some((w) => /duplicate/i.test(w))).toBe(true);
  });

  it('sanitises description — removes parentheses', async () => {
    const tool = { ...MINIMAL_TOOL, description: '1/2" (carbide) EM' };
    const result = await writeHaas([tool]);
    expect(result.content).not.toContain('(carbide)');
    // Description with parens stripped should still appear
    expect(result.content).toContain('1/2" carbide EM');
  });

  it('returns mime type text/plain', async () => {
    const result = await writeHaas([MINIMAL_TOOL]);
    expect(result.mimeType).toBe('text/plain');
  });

  it('warns on empty tool list', async () => {
    const result = await writeHaas([]);
    expect(result.warnings.length).toBeGreaterThan(0);
  });
});

// ── Round-trip tests ──────────────────────────────────────────────────────────

describe('HAAS round-trip', () => {
  it('preserves tool numbers and diameters through write → parse', async () => {
    const tools: Tool[] = [
      { id: 'a', toolNumber: 1, type: 'flat end mill', description: 'Rougher', unit: 'mm', geometry: { diameter: 12 }, offsets: { z: 200 } },
      { id: 'b', toolNumber: 5, type: 'drill',         description: 'Centre',  unit: 'mm', geometry: { diameter: 3  }, offsets: { z: 120 } },
    ];

    const written = await writeHaas(tools);
    const parsed  = await parseHaas(written.content, written.filename);

    expect(parsed.errors).toHaveLength(0);
    expect(parsed.tools).toHaveLength(2);
    expect(parsed.tools[0].toolNumber).toBe(1);
    expect(parsed.tools[0].geometry.diameter).toBeCloseTo(12);
    expect(parsed.tools[0].offsets?.z).toBeCloseTo(200);
    expect(parsed.tools[1].toolNumber).toBe(5);
    expect(parsed.tools[1].geometry.diameter).toBeCloseTo(3);
  });
});
