import { describe, it, expect } from 'vitest';
import { parseLinuxCNC } from '../../converters/linuxcnc/parser';
import { writeLinuxCNC } from '../../converters/linuxcnc/writer';
import type { Tool } from '../../types/tool';

// ── Fixtures ────────────────────────────────────────────────────────────────

const BASIC_TBL = `
;
T1 P1 X0.000000 Y0.000000 Z0.000000 A0.000000 B0.000000 C0.000000 U0.000000 V0.000000 W0.000000 D10.000000 I0.000000 J0.000000 Q0 ; 10mm Flat End Mill
T2 P2 X0.000000 Y0.000000 Z0.000000 A0.000000 B0.000000 C0.000000 U0.000000 V0.000000 W0.000000 D6.350000 I0.000000 J0.000000 Q0 ; 1/4in Ball End Mill
T10 P10 D4.000000 ; Short tool
`.trim();

const MINIMAL_TOOL: Tool = {
  id: 'test-id-1',
  toolNumber: 1,
  type: 'flat end mill',
  description: '10mm Flat End Mill',
  unit: 'mm',
  geometry: { diameter: 10 },
};

// ── Parser tests ─────────────────────────────────────────────────────────────

describe('LinuxCNC parser', () => {
  it('parses tool numbers and diameters', async () => {
    const result = await parseLinuxCNC(BASIC_TBL, 'test.tbl');
    expect(result.errors).toHaveLength(0);
    expect(result.tools).toHaveLength(3);

    expect(result.tools[0].toolNumber).toBe(1);
    expect(result.tools[0].geometry.diameter).toBe(10);

    expect(result.tools[1].toolNumber).toBe(2);
    expect(result.tools[1].geometry.diameter).toBeCloseTo(6.35);

    expect(result.tools[2].toolNumber).toBe(10);
    expect(result.tools[2].geometry.diameter).toBe(4);
  });

  it('uses trailing comment as description', async () => {
    const result = await parseLinuxCNC(BASIC_TBL, 'test.tbl');
    expect(result.tools[0].description).toBe('10mm Flat End Mill');
    expect(result.tools[1].description).toBe('1/4in Ball End Mill');
  });

  it('parses pocket number (P field)', async () => {
    const result = await parseLinuxCNC(BASIC_TBL, 'test.tbl');
    expect(result.tools[0].pocketNumber).toBe(1);
    expect(result.tools[1].pocketNumber).toBe(2);
  });

  it('falls back to T# as description when no comment', async () => {
    const result = await parseLinuxCNC('T5 P5 D8.000000', 'test.tbl');
    expect(result.tools[0].description).toBe('T5');
  });

  it('skips blank lines and the header semicolon', async () => {
    const result = await parseLinuxCNC(';\nT1 P1 D5.0 ; drill\n\n', 'test.tbl');
    expect(result.tools).toHaveLength(1);
  });

  it('skips pure comment lines', async () => {
    const result = await parseLinuxCNC('; this is a comment\nT1 P1 D5.0', 'test.tbl');
    expect(result.tools).toHaveLength(1);
  });

  it('warns when no tools found', async () => {
    const result = await parseLinuxCNC(';\n; only comments\n', 'empty.tbl');
    expect(result.tools).toHaveLength(0);
    expect(result.warnings.length).toBeGreaterThan(0);
  });

  it('preserves lathe fields (I, J, Q) in sourceData', async () => {
    const lathe = 'T1 P1 D25.4 I35.0 J50.0 Q2 ; lathe tool';
    const result = await parseLinuxCNC(lathe);
    expect(result.tools[0].sourceData?.frontAngle).toBe(35);
    expect(result.tools[0].sourceData?.backAngle).toBe(50);
    expect(result.tools[0].sourceData?.orientation).toBe(2);
  });

  it('handles ArrayBuffer input', async () => {
    const buf = new TextEncoder().encode('T3 P3 D12.0 ; buffer tool').buffer;
    const result = await parseLinuxCNC(buf);
    expect(result.tools[0].toolNumber).toBe(3);
    expect(result.tools[0].geometry.diameter).toBe(12);
  });
});

// ── Writer tests ──────────────────────────────────────────────────────────────

describe('LinuxCNC writer', () => {
  it('produces correct T, P, D fields', async () => {
    const result = await writeLinuxCNC([MINIMAL_TOOL]);
    expect(result.content).toContain('T1 ');
    expect(result.content).toContain('P1 ');
    expect(result.content).toContain('D10.000000');
  });

  it('sets output filename with .tbl extension', async () => {
    const result = await writeLinuxCNC([MINIMAL_TOOL], { filename: 'my-library.hsmlib' });
    expect(result.filename).toBe('my-library.tbl');
  });

  it('falls back to tool-table.tbl when no filename given', async () => {
    const result = await writeLinuxCNC([MINIMAL_TOOL]);
    expect(result.filename).toBe('tool-table.tbl');
  });

  it('writes header comment by default', async () => {
    const result = await writeLinuxCNC([MINIMAL_TOOL]);
    expect(result.content).toContain('; Generated by');
  });

  it('omits header comment when option is false', async () => {
    const result = await writeLinuxCNC([MINIMAL_TOOL], { linuxcncIncludeHeaderComment: false });
    expect(result.content).not.toContain('; Generated by');
  });

  it('respects decimal places option', async () => {
    const result = await writeLinuxCNC([MINIMAL_TOOL], { linuxcncDecimalPlaces: 2 });
    expect(result.content).toContain('D10.00 ');
  });

  it('applies tool number offset', async () => {
    const result = await writeLinuxCNC([MINIMAL_TOOL], { linuxcncStartingToolNumber: 100 });
    expect(result.content).toContain('T101 ');
  });

  it('warns when no tools provided', async () => {
    const result = await writeLinuxCNC([]);
    expect(result.warnings.length).toBeGreaterThan(0);
  });

  it('warns on duplicate tool numbers', async () => {
    const dup = { ...MINIMAL_TOOL, id: 'test-id-2' };
    const result = await writeLinuxCNC([MINIMAL_TOOL, dup]);
    expect(result.warnings.some((w) => w.includes('Duplicate'))).toBe(true);
  });

  it('uses sequential pocket assignment when option set', async () => {
    const tools: Tool[] = [
      { ...MINIMAL_TOOL, toolNumber: 5, pocketNumber: 99 },
      { ...MINIMAL_TOOL, id: 'b', toolNumber: 6, pocketNumber: 99 },
    ];
    const result = await writeLinuxCNC(tools, { linuxcncPocketAssignment: 'sequential' });
    const lines = result.content.split('\n').filter((l) => l.startsWith('T'));
    expect(lines[0]).toContain('P1 ');
    expect(lines[1]).toContain('P2 ');
  });
});

// ── Round-trip test ───────────────────────────────────────────────────────────

describe('LinuxCNC round-trip', () => {
  it('parse → write → parse preserves tool number and diameter', async () => {
    const first = await parseLinuxCNC(BASIC_TBL, 'test.tbl');
    const written = await writeLinuxCNC(first.tools, { linuxcncIncludeHeaderComment: false });
    const second = await parseLinuxCNC(written.content, 'test.tbl');

    expect(second.tools).toHaveLength(first.tools.length);
    for (let i = 0; i < first.tools.length; i++) {
      expect(second.tools[i].toolNumber).toBe(first.tools[i].toolNumber);
      expect(second.tools[i].geometry.diameter).toBeCloseTo(first.tools[i].geometry.diameter);
      expect(second.tools[i].description).toBe(first.tools[i].description);
    }
  });
});
