/**
 * Fanuc Tool Offset Table Writer (G10 punch format — Memory C)
 *
 * Produces a G-code file using G10 programmable data input that can be
 * loaded into a Fanuc 0i-MF / 31i / 35i control via RS-232 or USB:
 *
 *   %
 *   O9999 (TOOL OFFSETS - GENERATED BY CNC TOOL CONVERTER)
 *   (GEOMETRY OFFSETS)
 *   G10 L10 P1 R200.0000  (T1 - H GEOMETRY)
 *   G10 L11 P1 R0.0000    (T1 - H WEAR)
 *   G10 L12 P1 R6.3500    (T1 - D GEOMETRY)
 *   G10 L13 P1 R0.0000    (T1 - D WEAR)
 *   ...
 *   M30
 *   %
 *
 * Notes:
 *  - L10 = H geometry (from offsets.z)
 *  - L11 = H wear (from sourceData.fanucLenWear, else 0)
 *  - L12 = D geometry (from geometry.diameter)
 *  - L13 = D wear (from sourceData.fanucDiaWear, else 0)
 *  - P word is the register number (= tool number)
 *  - R values are in machine units; assumes mm (caller responsibility)
 */

import type { Tool } from '../../types/tool';
import type { WriteResult, WriteOptions } from '../../types/converter';

function f(val: number | undefined, decimals = 4): string {
  return (val ?? 0).toFixed(decimals);
}

export async function writeFanuc(
  tools: Tool[],
  options?: WriteOptions,
): Promise<WriteResult> {
  const warnings: string[] = [];

  if (tools.length === 0) warnings.push('No tools to write.');

  const nums = tools.map((t) => t.toolNumber);
  const dups = nums.filter((n, i) => nums.indexOf(n) !== i);
  if (dups.length) {
    warnings.push(`Duplicate tool numbers (P registers): ${[...new Set(dups)].join(', ')}.`);
  }

  const lines: string[] = [
    '%',
    'O9999 (TOOL OFFSETS - GENERATED BY CNC TOOL CONVERTER)',
    '(H = LENGTH GEOMETRY/WEAR, D = DIAMETER GEOMETRY/WEAR)',
    'G90',
  ];

  for (const tool of tools) {
    const sd      = (tool.sourceData ?? {}) as Record<string, number>;
    const P       = tool.toolNumber;
    const lenGeo  = tool.offsets?.z ?? 0;
    const lenWear = sd.fanucLenWear ?? 0;
    const diaGeo  = tool.geometry.diameter;
    const diaWear = sd.fanucDiaWear ?? 0;

    // Sanitise description for G-code comment (no parens)
    const desc = (tool.description ?? `T${P}`).replace(/[()]/g, '').substring(0, 30).trimEnd();

    lines.push(`G10 L10 P${P} R${f(lenGeo)} (T${P} H GEO - ${desc})`);
    lines.push(`G10 L11 P${P} R${f(lenWear)} (T${P} H WEAR)`);
    lines.push(`G10 L12 P${P} R${f(diaGeo)} (T${P} D GEO)`);
    lines.push(`G10 L13 P${P} R${f(diaWear)} (T${P} D WEAR)`);
  }

  lines.push('M30');
  lines.push('%');

  const baseName = (options?.filename as string | undefined)?.replace(/\.[^.]+$/, '') ?? 'fanuc-offsets';

  return {
    content:  lines.join('\r\n') + '\r\n',
    filename: `${baseName}.nc`,
    mimeType: 'text/plain',
    warnings,
  };
}
