import type { Converter } from '../../types/converter';
import { parseHaas } from './parser';
import { writeHaas } from './writer';

export const haasConverter: Converter = {
  format: {
    id:             'haas',
    name:           'HAAS',
    description:    'HAAS CNC tool offset table — Format A (.ofs)',
    fileExtensions: ['.ofs', '.ngc', '.nc'],
    mimeTypes:      ['text/plain'],
    canImport:      true,
    canExport:      true,
    readAs:         'text',
  },
  sample: [
    '%',
    '(TOOL OFFSETS - Generated by CNC Tool Converter)',
    '(  TOOL  LENGTH GEOMETRY  LENGTH WEAR   DIA GEOMETRY   DIA WEAR  DESCRIPTION        CLNT POS)',
    '(    1     200.0000         0.0000        12.7000         0.0000   1/2 ENDMILL               0)',
    '(    2     195.3750         0.0050         6.3500         0.0010   1/4 DRILL                 0)',
    '(    3     182.0000         0.0000         9.5250         0.0000   3/8 BALL MILL             0)',
    '%',
  ].join('\n'),
  parse: (content, filename) => parseHaas(content, filename),
  write: (tools, options)    => writeHaas(tools, options),
};
