/**
 * HAAS Tool Offset Table Writer
 *
 * Produces Format A output (the modern NGC-compatible format):
 *
 *   % (TOOL OFFSETS)
 *   (  TOOL  LENGTH GEOMETRY  LENGTH WEAR   DIA GEOMETRY   DIA WEAR  DESCRIPTION  CLNT POS)
 *   (    1     200.0000         0.0000        0.5000         0.0000   1/2 ENDMILL       0)
 *   %
 *
 * Notes:
 *  - LENGTH GEOMETRY ← offsets.z (if present), otherwise 0
 *  - DIA GEOMETRY    ← geometry.diameter (full diameter, Setting 40 = diameter mode)
 *  - LENGTH WEAR / DIA WEAR ← restored from sourceData if available, else 0
 *  - DESCRIPTION is truncated to 16 chars to fit the HAAS display
 *  - CLNT POS defaults to 0 (standard nozzle position)
 */

import type { Tool } from '../../types/tool';
import type { WriteResult, WriteOptions } from '../../types/converter';

function f(val: number | undefined, decimals = 4): string {
  return (val ?? 0).toFixed(decimals);
}

function pad(s: string, width: number, right = false): string {
  if (right) return s.padEnd(width);
  return s.padStart(width);
}

export async function writeHaas(
  tools: Tool[],
  options?: WriteOptions,
): Promise<WriteResult> {
  const warnings: string[] = [];

  if (tools.length === 0) warnings.push('No tools to write.');

  // Check for duplicate tool numbers
  const nums = tools.map((t) => t.toolNumber);
  const dups = nums.filter((n, i) => nums.indexOf(n) !== i);
  if (dups.length) {
    warnings.push(`Duplicate tool numbers: ${[...new Set(dups)].join(', ')}.`);
  }

  const lines: string[] = [
    '%',
    '(TOOL OFFSETS - Generated by CNC Tool Converter)',
    '(  TOOL  LENGTH GEOMETRY  LENGTH WEAR   DIA GEOMETRY   DIA WEAR  DESCRIPTION        CLNT POS)',
  ];

  for (const tool of tools) {
    const sd       = (tool.sourceData ?? {}) as Record<string, number>;
    const lenGeo   = tool.offsets?.z ?? 0;
    const lenWear  = sd.haasLengthWear ?? 0;
    const diaGeo   = tool.geometry.diameter;
    const diaWear  = sd.haasDiaWear ?? 0;
    const clntPos  = sd.haasClntPos ?? 0;
    // Truncate + sanitise description (no parentheses — they close the comment)
    const desc     = (tool.description ?? `T${tool.toolNumber}`)
      .replace(/[()]/g, '')
      .substring(0, 20)
      .trimEnd();

    // Build the line with approximate column alignment matching HAAS display
    const toolCol  = pad(String(tool.toolNumber), 5);
    const lgCol    = pad(f(lenGeo),  12);
    const lwCol    = pad(f(lenWear), 12);
    const dgCol    = pad(f(diaGeo),  13);
    const dwCol    = pad(f(diaWear), 11);
    const descCol  = pad(desc, 20, true);
    const clntCol  = pad(String(clntPos), 5);

    lines.push(`(${toolCol} ${lgCol}  ${lwCol}  ${dgCol}  ${dwCol}  ${descCol} ${clntCol})`);
  }

  lines.push('%');

  const baseName = (options?.filename as string | undefined)?.replace(/\.[^.]+$/, '') ?? 'haas-offsets';

  return {
    content:  lines.join('\r\n') + '\r\n',
    filename: `${baseName}.ofs`,
    mimeType: 'text/plain',
    warnings,
  };
}
