/**
 * LinuxCNC Tool Table (.tbl) Writer
 *
 * Produces a plain-text tool table compatible with LinuxCNC 2.4.x and later.
 *
 * Output format:
 *   ;
 *   T{n} P{p} X{x} Y{y} Z{z} A{a} B{b} C{c} U{u} V{v} W{w} D{dia} I{fa} J{ba} Q{ori} ; comment
 *
 * Notes on conversion from the internal model:
 *  - Z offset is set to 0 (tool must be measured on the actual machine)
 *  - All unused axis offsets are written as 0
 *  - The tool description becomes the trailing comment
 *  - Lathe-specific fields I, J, Q default to 0 for milling tools
 */

import type { Tool } from '../../types/tool';
import type { WriteResult, WriteOptions } from '../../types/converter';

function fmt(val: number | undefined, decimals: number): string {
  return (val ?? 0).toFixed(decimals);
}

export async function writeLinuxCNC(
  tools: Tool[],
  options?: WriteOptions,
): Promise<WriteResult> {
  const warnings: string[] = [];

  // ── Writer options from settings ─────────────────────────────────────────
  const decimals             = typeof options?.linuxcncDecimalPlaces === 'number'
    ? options.linuxcncDecimalPlaces : 6;
  const tOffset              = typeof options?.linuxcncStartingToolNumber === 'number'
    ? Math.max(0, options.linuxcncStartingToolNumber) : 0;
  const pocketAssignment     = options?.linuxcncPocketAssignment === 'sequential'
    ? 'sequential' : 'match-t';
  const includeHeaderComment = options?.linuxcncIncludeHeaderComment !== false;

  if (tools.length === 0) {
    warnings.push('No tools to write.');
  }

  // Warn if any tools share a tool number (LinuxCNC requires unique T numbers)
  const toolNumbers = tools.map((t) => t.toolNumber + tOffset);
  const duplicates  = toolNumbers.filter((n, i) => toolNumbers.indexOf(n) !== i);
  if (duplicates.length > 0) {
    warnings.push(
      `Duplicate tool numbers detected: ${[...new Set(duplicates)].join(', ')}. ` +
      `LinuxCNC requires unique T numbers.`,
    );
  }

  const lines: string[] = [];

  if (includeHeaderComment) {
    lines.push('; Generated by CNC Tool Converter');
  }

  tools.forEach((tool, index) => {
    const offsets = tool.offsets ?? {};
    const sd      = tool.sourceData ?? {};

    const T = tool.toolNumber + tOffset;

    // Pocket number
    const P = pocketAssignment === 'sequential'
      ? index + 1
      : (tool.pocketNumber ?? T);

    // Axis offsets
    const X = fmt(offsets.x, decimals);
    const Y = fmt(offsets.y, decimals);
    const Z = fmt(offsets.z, decimals);
    const A = fmt(offsets.a, decimals);
    const B = fmt(offsets.b, decimals);
    const C = fmt(offsets.c, decimals);
    const U = fmt(offsets.u, decimals);
    const V = fmt(offsets.v, decimals);
    const W = fmt(offsets.w, decimals);

    const D = fmt(tool.geometry.diameter, decimals);

    // Lathe fields (0 for milling tools)
    const I = fmt(sd.frontAngle  as number | undefined, decimals);
    const J = fmt(sd.backAngle   as number | undefined, decimals);
    const Q = Math.round((sd.orientation as number | undefined) ?? 0).toString();

    // Sanitise comment — no semicolons inside
    const comment = (tool.description ?? `T${T}`).replace(/;/g, ',');

    const line = [
      `T${T}`,
      `P${P}`,
      `X${X}`, `Y${Y}`, `Z${Z}`,
      `A${A}`, `B${B}`, `C${C}`,
      `U${U}`, `V${V}`, `W${W}`,
      `D${D}`,
      `I${I}`, `J${J}`, `Q${Q}`,
      `; ${comment}`,
    ].join(' ');

    lines.push(line);
  });

  const sourceFile = options?.filename as string | undefined;
  const baseName   = sourceFile
    ? sourceFile.replace(/\.[^.]+$/, '')
    : 'tool-table';

  return {
    content:  lines.join('\n') + '\n',
    filename: `${baseName}.tbl`,
    mimeType: 'text/plain',
    warnings,
  };
}
